# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "site"
destination:    ./_gh_pages
host:           "localhost"
port:           9001
baseurl:        ""
# boosted mod
url:            "https://boosted.orange.com"
# end boosted mod
encoding:       UTF-8
exclude:
  - docs/4.4/assets/scss/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

redirect_from:
  json: false

# boosted mod
grid:
  xs:
    breakpoint: 0
    width: 302
    gutter: 10
    desc: Extra small devices
    subdesc: Portrait phone (&lt;480px) (target 320 screen resolutions)
  sm:
    breakpoint: 480
    width: 458
    gutter: 10
    desc: Small devices
    subdesc: Landscape phones (&ge;480px - &lt;768px) (target 480 screen resolutions)
  md:
    breakpoint: 768
    width: 724
    gutter: 20
    desc: Medium devices
    subdesc: Tablet (&ge;768px - &lt;960px) (target 768 screen resolutions)
  lg:
    breakpoint: 980
    width: 960
    gutter: 20
    desc: Large devices
    subdesc: Desktop (&ge;960px - &lt;1120px) (target 1024 screen resolutions)
  xl:
    breakpoint: 1220
    width: 1180
    gutter: 20
    desc: Extra large devices
    subdesc: Desktop (&ge;1220px - &lt;1380px) (target 1280 screen resolutions)
  xxl:
    breakpoint: 1380
    width: 1300
    gutter: 20
    desc: Extra extra large devices
    subdesc: Desktop (&ge;1380px) (target 1440 screen resolutions)
# end boosted mod

# Social
title:              Boosted
description:        "Orange HTML, CSS and JS library — based on Bootstrap, the most popular library."
twitter:            orange
authors:            "Orange and Boosted contributors"
social_image_path:  /docs/4.4/assets/brand/orange-social.png
social_logo_path:   /docs/4.4/assets/brand/orange-logo.png

# Custom variables
current_version:      4.4.1
current_ruby_version: 4.4.1
docs_version:         4.4
github_org:           "https://github.com/Orange-OpenSource"
repo:                 "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap"
slack:                "https://bootstrap-slack.herokuapp.com"
opencollective:       "https://opencollective.com/bootstrap"
blog:                 "https://blog.getbootstrap.com"
expo:                 "https://expo.getbootstrap.com"
themes:               "https://themes.getbootstrap.com"
icons:                "https://icons.getbootstrap.com"

download:
  source:           "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v4.4.1.zip"
  dist:             "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v4.4.1/boosted-4.4.1-dist.zip"
  dist_examples:    "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v4.4.1/boosted-4.4.1-examples.zip"
cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:               "https://cdn.jsdelivr.net/npm/boosted@4.4.1/dist/css/boosted.min.css"
  css_hash:          "sha384-OB/gcmnjN4zOvILOKtMqzd/ZUoKc/cgZDpn0c2C5FoQAJqmQdjX4ITe6XSK32JyO"
  iconcss:           "https://cdn.jsdelivr.net/npm/boosted@4.4.1/dist/css/orangeIcons.min.css"
  iconcss_hash:      "sha384-Zd5WIT6PZ7YtONlsULMAoLWo0iJi5GPix2LFrMhPQjMYjBA0FhvsKInWdLKM+9nW"
  helveticacss:      "https://cdn.jsdelivr.net/npm/boosted@4.4.1/dist/css/orangeHelvetica.min.css"
  helveticacss_hash: "sha384-e8MwV9etVvzgFAywWdlyEtXAdRYElY+BlimyrAcXkDiyJXy4oIZZqrV/ST605uwF"
  js:                "https://cdn.jsdelivr.net/npm/boosted@4.4.1/dist/js/boosted.min.js"
  js_hash:           "sha384-Y/0NjLXRerXrg7jzex/E5ONTjY9VxGnhnsY0dVw12hlg/0XlAJFjh1biCQfdWI1R"
  js_bundle:         "https://cdn.jsdelivr.net/npm/boosted@4.4.1/dist/js/boosted.bundle.min.js"
  js_bundle_hash:    "sha384-YMZ99KioGrdm3FGH96tSA1P9XAvOIwB58TjPJkyI6QEREIBiYpsufL3KXgF4FlSo"
  jquery:           "https://code.jquery.com/jquery-3.5.1.slim.min.js"
  jquery_hash:      "sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
  css_swiper:        "https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/css/swiper.min.css"
  css_swiper_hash:   "sha384-K6LrEaceM4QP87RzJ7R4CDXcFN4cFW/A5Q7/fEp/92c2WV+woVw9S9zKDO23sNS+"
  js_swiper:         "https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/js/swiper.min.js"
  js_swiper_hash:    "sha384-fOtis9P3S4B2asdoye1/YBpXMaRmuXu925gZhfQA/gnU3dLnftD8zvpk/lhP0YSG"
  popper:            "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js"
  popper_hash:       "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  tablesorter:       "https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.1/js/jquery.tablesorter.min.js"
  tablesorter_hash:  "sha384-QnFIXbEfAgO7z63b/aNzTSdSNLoNiNX/mk/Ok+NpUNMnvriWLo5cOtB0OUCAdKNu"
  js_docsearch:      "https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"
  js_docsearch_hash: "sha384-8uEk67aWSZHvjtAX9hf2AB+KzYcssy31vRRTi9oP81zHtyIj7PQGAykGbQpB1L2J"

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"
